language: node_js
node_js: 
  - node
env:
  -CI=false
cache: 
  directories: 
    - node_modules
install: 
  - npm install
script: 
  - npm run build
  - npm run coverage
deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
